on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: smartcitye2e1.azurecr.io
        username: ${{ secrets.acr_smartcitye2e1_username }}
        password: ${{ secrets.acr_smartcitye2e1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ref-apps/rocket/csharp" -f  "ref-apps/rocket/csharp/Dockerfile" -t smartcitye2e1.azurecr.io/smartcitykubernetes1:${{ github.sha }} --label dockerfile-path=ref-apps/rocket/csharp/Dockerfile
        docker push smartcitye2e1.azurecr.io/smartcitykubernetes1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_smartcitykubernetes1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep smartcity-kubernetes-1bbc4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace smartcity-kubernetes-1bbc4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: smartcity-kubernetes-1bbc4
        container-registry-url: smartcitye2e1.azurecr.io
        container-registry-username: ${{ secrets.acr_smartcitye2e1_username }}
        container-registry-password: ${{ secrets.acr_smartcitye2e1_password }}
        secret-name: smartcitykubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: smartcity-kubernetes-1bbc4
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          smartcitye2e1.azurecr.io/smartcitykubernetes1:${{ github.sha }}
        imagepullsecrets: |
          smartcitykubdockerauth
